#!/bin/bash
git add .
git ci -m "redeploying"
git push

kubectl --namespace jbo patch deployment python-demo-app -p \
  "{\"spec\":{\"template\":{\"metadata\":{\"labels\":{\"date\":\"`date +'%s'`\"}}}}}"
