#!/bin/bash

set -x
./build

git add .
git ci -m "redeploying"
git push

sleep 20

kubectl --namespace jbo delete -f my_app.yaml

sleep 5

kubectl --namespace jbo apply -f my_app.yaml

#kubectl --namespace jbo patch deployment python-demo-app -p \
#  "{\"spec\":{\"template\":{\"metadata\":{\"labels\":{\"date\":\"`date +'%s'`\"}}}}}"
